version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: clothing_mongodb
    restart: always
    ports:
      - "27555:27017"
    environment:
      MONGO_INITDB_DATABASE: clothing_db
    volumes:
      - ./mongo/data:/data/db
      - ./mongo/init.js:/docker-entrypoint-initdb.d/init.js:ro
    networks:
      - clothing_network

networks:
  clothing_network:
    driver: bridge
